#!/usr/bin/env python

""" 
one sheet per tsv in the current directory.
Usage: excel_tsv 1.xlsx 2.xlsx
"""
from __future__ import print_function
import sys
import pandas as pd

def process(excel):
    print('\nconverting:') 
    fname = excel.split('/')[-1].split('.')[0]
    # xls is a dict {'sheet name': pd.DataFrame}
    xls = pd.read_excel(excel, sheetname = None)
    for k, v in zip(xls.keys(), xls.values()):
        tsv = ('%s_%s.%s' % (fname, k, 'tsv')) 
        v.to_csv(tsv, sep = '\t', index=False)
        print(tsv) 

def main():
    for file in sys.argv[1:]:
        print('\nreading:', file)
        process(file)

if __name__ == '__main__':
    main()
